GET http://localhost:8880/hello
Accept: application/json

###
POST http://localhost:8880/hello/post
Content-Type: application/x-www-form-urlencoded

name=TEST

###
GET http://localhost:8880/test/list

###

